### ISSUE TITLE
Can not find the `xspecfem3D` binary

### ISSUE THREAD

**Issue by AymenFJA** [lsawade/simple_entk_specfem#3]
Hello @lsawade. This is Aymen from the RADICAL-Lab. I was assigned to follow up on your issue regarding running your code with EnTK on summit. Some work has been done on the scheduling level of the GPU tasks, and we want to test it again on summit. 

Also, we have a tickets (https://github.com/radical-cybertools/radical.pilot/issues/2831) and a PR (https://github.com/radical-cybertools/radical.entk/pull/636) for you so that you can follow up on our latest progress to solve the issue.

Currently we tried to run the `solver.py`, but we could not find the executable of `task1` and `task2` (`./bin/xspecfem3D`) 

Can you point us to the location of that executable please?

**Comment by lsawade** [comment]
Hi @AymenFJA! Thanks for looking into this.

Oh boi, I didn't test the `solver.py` thoroughly since not even the `hello world` was working. There was a typo in the way task directory, which is defined [here solver.py#L64](https://github.com/lsawade/simple_entk_specfem/blob/9f5d0845426bbb9678b54348003a2e5009374884/solver.py#L64) and the task preexecutables should switch to the directory [here solver.py#L71](https://github.com/lsawade/simple_entk_specfem/blob/9f5d0845426bbb9678b54348003a2e5009374884/solver.py#L71). 

Could you try again?

---

For background, the original executable is here:
```bash
 /gpfs/alpine/geo111/scratch/lsawade/SpecfemMagic/specfem3d_globe/bin
```
However, I'm using other directories to run specfem, which is how we run 'big runs'.

```bash
/gpfs/alpine/geo111/scratch/lsawade/entk_test/specfem_run_1/bin -> /gpfs/alpine/geo111/scratch/lsawade/SpecfemMagic/specfem3d_globe/bin
/gpfs/alpine/geo111/scratch/lsawade/entk_test/specfem_run_2/bin -> /gpfs/alpine/geo111/scratch/lsawade/SpecfemMagic/specfem3d_globe/bin
```

So, the directory that the tasks should be executed from should be 

```bash
/gpfs/alpine/geo111/scratch/lsawade/entk_test/specfem_run_1
```
and
```
/gpfs/alpine/geo111/scratch/lsawade/entk_test/specfem_run_2
```

In either you should be able to call
```bash
./bin/xspecfem3D
```

**Comment by AymenFJA** [comment]
@lsawade, thanks for your response. I do not have permission to access your directory on Summit, which is expected.
```
[aymen@login2.summit simple_entk_specfem]$ cd /gpfs/alpine/geo111/scratch/lsawade/SpecfemMagic/specfem3d_globe/bin
-bash: cd: /gpfs/alpine/geo111/scratch/lsawade/SpecfemMagic/specfem3d_globe/bin: Permission denied
[aymen@login2.summit simple_entk_specfem]$
```

Would it be possible to upload the binary or the executable here please?

**Comment by lsawade** [comment]
Hi @AymenFJA, i don't think that's going to work as the executable needs to be run from the directory. Or, (shallow) copy of the directory, see `/gpfs/alpine/geo111/scratch/lsawade/entk_test`.

I tried 
```bash 
chmod -R 777 /gpfs/alpine/geo111/scratch/lsawade/entk_test
```
can you try to

```bash
cd /gpfs/alpine/geo111/scratch/lsawade/entk_test/specfem_run_1
```

and just try `./bin/xspecfem3D`, which should throw an error because wrong number of MPI slices.

**Comment by mturilli** [comment]
Could we use `Project Work -- /gpfs/alpine/[projid]/proj-shared` or, if we still need to get Aymen on your project, `World Work -- /gpfs/alpine/[projid]/world-shared`?

**Comment by lsawade** [comment]
@mturilli good point. I'm going to copy it to `world-shared` to be safe. Technically, I am already trying to do that, but it seems like the file system is really slow at the moment. I'll update once done.

**Comment by lsawade** [comment]
both `specfem3d_globe` and `entk_test` are now in `/gpfs/alpine/geo111/world-shared/lsawade` and the repo has been updated in terms of `solver.py`.

**Comment by AymenFJA** [comment]
@lsawade, thank you. I can access the files now and use them. But I stumbled upon this error: 

```
/gpfs/alpine/geo111/world-shared/lsawade/specfem3d_globe/bin/xspecfem3D: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No such file or directory
```
Is there any module that I need to load before running this executable?

**Comment by AymenFJA** [comment]
@lsawade any idea please, or suggestions?

**Comment by mtitov** [comment]
side comment: update GPU requirements in `solver.py` as following: `t.gpu_reqs = {'gpu_processes': 1,  'gpu_process_type': 'CUDA'}` - having `CUDA` set, triggers EnTK/RP to set env variable `CUDA_VISIBLE_DEVICES`

**Comment by lsawade** [comment]
Sorry @AymenFJA, I lost track if this one. I updated `solver.py` with @mtitov's correction and changed the modules that are loaded in `task.pre_exec` to
```bash
module load gcc/7.5.0 spectrum-mpi cuda cmake boost
```
which are the modules that were loaded for compilation.

**Comment by AymenFJA** [comment]
@lsawade, thanks for your response. It is partially running now, but task.0001 fails, and the error comes from the binary:
```
Warning: more than 1 task/rank assigned to a core
Error testing memory allocation on device failed
Error rank 2: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 6: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 3: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 7: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 19: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 20: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 8: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 5: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 15: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 11: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 17: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 16: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 13: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 14: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 9: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 23: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


Error testing memory allocation on device failed
Error rank 21: cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Please check GPU settings on your node


--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 6 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 7 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed



ERROR: CUDA runtime error: cudaMalloc failed

```

we are using the same take resource requirements in the solver.py for GPU and CPU tasks. Any idea if we are doing something wrong here?

**Comment by lsawade** [comment]
When you ask for your allocation 
```bsub ... -alloc_flags "gpumps smt1" ...```
are you asking for gpumps?

**Comment by AymenFJA** [comment]
@lsawade yes, correct. These flags are already set through my batch script.

**Comment by mtitov** [comment]
@lsawade @AymenFJA I was able to run it successfully - corresponding task didn't produce anything, but STDERR still has a warning: `Warning: more than 1 task/rank assigned to a core`

I did copy the whole directory `/gpfs/alpine/geo111/world-shared/lsawade/specfem3d_globe` into my space (and used it in the task's pre_exec list `f'cd {my_work_dir}'`

Updated task requirements are:
```python
t.cpu_reqs = {'cpu_processes': 24, 'cpu_threads': 1, 'cpu_thread_type' : 'OpenMP'}
t.gpu_reqs = {'gpu_processes': .25, 'gpu_process_type': 'CUDA'}
```
which produced the following launch command
```
/opt/ibm/jsm/bin/jsrun -n6 -a4 -c4 -g1 -r6 -b packed:4 --smpiargs="-gpu" ...
```

---

when I used script `mkspecfemdirs` to get executables from `specfem3d_globe` I had the following error
```
$ cat STD*
Warning: more than 1 task/rank assigned to a core
At line 57 of file src/shared/exit_mpi.f90 (unit = 30)
Fortran runtime error: Cannot open file './OUTPUT_FILES///error_message000000.txt': Read-only file system

Error termination. Backtrace:
 Error opening file output_solver.txt for writing output info
 Error detected, aborting MPI... proc            0
```

**Comment by mtitov** [comment]
small update - that warning is due to the binding option we use (`-b rs` or `-b packed:<cores_per_rs>`), without any binding there is no warning - I'll review the importance of setting that binding

**Comment by lsawade** [comment]
@AymenFJA can you just try to get an interactive allocation and use the line that @mtitov is producing without the -b option, and see whether you can run it "manually"?

**Comment by mtitov** [comment]
@lsawade Hi Lucas, I think we don't need to focus on Aymen's runs, since that was part of our testing. I've prepared PR to fix the binding option (RP PR [#2844](https://github.com/radical-cybertools/radical.pilot/pull/2844)), so it is about to be merged into devel-branch. Thus, you can try these updates on your own, and here are several points to consider
- resource description: `'resource': 'ornl.summit_jsrun'`
- check the amount of resources you request for, e.g., with the current setting you ask for 8 nodes (==48 GPUs)
- update task requirements
```python
t.cpu_reqs = {'cpu_processes':  24, 'cpu_threads': 1, 'cpu_thread_type' : 'OpenMP'}
t.gpu_reqs = {'gpu_processes': .25, 'gpu_process_type': 'CUDA'}
```
- use the latest versions for RP and EnTK
```
pip install git+https://github.com/radical-cybertools/radical.pilot.git@devel
pip install git+https://github.com/radical-cybertools/radical.entk.git@devel
```

**Comment by lsawade** [comment]
Hi @mtitov, hi @AymenFJA,

I just tested it with a single node, and it worked!!!

I am now testing with a multiple nodes, but it should just work I assume.

Will report back soon.

**Comment by lsawade** [comment]
It ran without issues!

**Comment by AymenFJA** [comment]
Congrats, @lsawade. Thanks for letting us know. This ticket can be closed now, and please feel free to open a new ticket if you face any other problems with RCT.
